name: Acceptance Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  e2e-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: ats/run
